# -*- coding: utf-8 -*-
"""DC EXP-1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXxYLYpKABnowV7MoirpZ0XcJJEfuF1u

**IDEAL SAMPLING**

**DHEVI BALA SHREE P**

**212224060063**
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import resample

fs = 100
t = np.arange(0, 1, 1/fs)
f = 5
signal = np.sin(2 * np.pi * f * t)

# Sampled signal
t_sampled = np.arange(0, 1, 1/fs)
signal_sampled = np.sin(2 * np.pi * f * t_sampled)

# Reconstructed signal
reconstructed_signal = resample(signal_sampled, len(t))

# Create subplots
plt.figure(figsize=(12, 8))

# 1. Continuous Signal
plt.subplot(3,1,1)
plt.plot(t, signal, label='Continuous Signal')
plt.title('Continuous Signal (fs = 100 Hz)')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.grid(True)
plt.legend()

# 2. Sampled Signal
plt.subplot(3,1,2)
plt.stem(t_sampled, signal_sampled, linefmt='r-', markerfmt='ro', basefmt='r-', label='Sampled Signal (fs = 100 Hz)')
plt.title('Sampling of Continuous Signal (fs = 100 Hz)')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.grid(True)
plt.legend()

# 3. Reconstructed Signal
plt.subplot(3,1,3)
plt.plot(t, reconstructed_signal, 'r--', label='Reconstructed Signal (fs = 100 Hz)')
plt.title('Reconstruction of Sampled Signal (fs = 100 Hz)')
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()